[package]
name = "tools-cli"
version = "0.1.0"
description = "Development tools"
authors = ["Yogafire <yogafirew@gmail.com>"]
edition = "2021"

[dependencies]
clap = "4.0"
chrono = "0.4"
data-encoding = "2.3"
serde = "1.0"
serde_json = "1.0"
